<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>scead</groupId>
        <artifactId>llminthehouse-parent</artifactId>
        <version>0.0.1</version>
    </parent>

    <artifactId>llminthehouse-backend</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.ws.rs</groupId>
            <artifactId>jakarta.ws.rs-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>tools.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
        </dependency>
        <dependency>
            <groupId>tools.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
        </dependency>
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <executions>
                    <!-- BE API Java Classes -->
                    <execution>
                        <id>Generate Java API Classes</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <generatorName>spring</generatorName>
                            <generateApis>true</generateApis>
                            <generateModels>true</generateModels>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <skipIfSpecIsUnchanged>true</skipIfSpecIsUnchanged>
                            <output>target/generated-sources</output>
                            <configOptions>
                                <useTags>true</useTags>
                                <sourceFolder>src/main/java</sourceFolder>
                                <dateLibrary>java8-localdatetime</dateLibrary>
                                <interfaceOnly>true</interfaceOnly>
                                <java8>true</java8>
                                <skipDefaultInterface>true</skipDefaultInterface>
                                <useJakartaEe>true</useJakartaEe>
                            </configOptions>
                            <inputSpec>
                                ${project.basedir}/src/main/resources/openapi/llminthehouse-api.yaml
                            </inputSpec>
                            <packageName>
                                scead.llminthehouse.base.channel.web
                            </packageName>
                            <modelPackage>
                                scead.llminthehouse.base.channel.web.dto
                            </modelPackage>
                            <apiPackage>
                                scead.llminthehouse.base.channel.web
                            </apiPackage>
                        </configuration>
                    </execution>
                    <!-- BE API Documentation -->
                    <execution>
                        <id>cbs-permission-provider</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>
                                ${project.basedir}/src/main/resources/openapi/llminthehouse-api.yaml
                            </inputSpec>
                            <generatorName>html</generatorName>
                            <output>${project.build.directory}/generated-documentation</output>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- copy api documentation to root -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-api-documentation</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.parent.basedir}/src/documentation/api</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.build.directory}/generated-documentation</directory>
                                    <includes>
                                        <include>index.html</include>
                                    </includes>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>